import { z } from "zod";

import { ids } from "../../models/Ids";

export const schema = z.object({
	[ids.certificateConclusion]: z.string(),
	[ids.certificateFormNote]: z.string(),
	[ids.certificateFormStatus]: z.string(),
	[ids.certificateIssueDate]: z.string(),
	[ids.certificateIssueNo]: z.string().nullable(),
	[ids.certificateQualityDescription]: z.string(),
	[ids.certificateRemarkDescription]: z.string(),
	[ids.creditDocumentExpireDate]: z.string(),
	[ids.creditDocumentNo]: z.string(),
	[ids.creditDocumentStartDate]: z.string(),
	[ids.creditOpeningBankBranch]: z.string(),
	[ids.creditOpeningBankName]: z.string(),
	[ids.creditNegotiatingBankBranch]: z.string(),
	[ids.creditNegotiatingBankName]: z.string(),
	[ids.goodsDescriptions]: z.string(),
	[ids.goodsGrossWeight]: z.string(),
	[ids.goodsShippingBasis]: z.string(),
	[ids.goodsShippingDestinationCity]: z.string(),
	[ids.goodsShippingDestinationSite]: z.string(),
	[ids.goodsShippingDueDate]: z.string(),
	[ids.goodsShippingMethod]: z.string(),
	[ids.goodsShippingSourceCity]: z.string(),
	[ids.goodsShippingSourceSite]: z.string(),
	[ids.inspectionDate]: z.string(),
	[ids.inspectionPlace]: z.string(),
	[ids.invoiceDate]: z.string(),
	[ids.invoiceNo]: z.string(),
	[ids.invoiceNoArray]: z.array(z.object({ no: z.string(), date: z.string() })),
	[ids.proceedingsDate]: z.string(),
	[ids.proceedingsNo]: z.string(),
	[ids.proformaDate]: z.string(),
	[ids.proformaNo]: z.string(),
	[ids.seller]: z.string(),
});
