import { MappingTypeMapping } from '@elastic/elasticsearch/lib/api/types';

export const invoiceMapping: MappingTypeMapping = {
  properties: {
    id: { type: 'keyword' },
    title: { type: 'text' }, 
    description: { type: 'text' }, 
    status: { type: 'text' }, 
    type: { type: 'text' }, 
    expiryAt: { type: 'date' }, 
    issuedAt: { type: 'date' }, 
    items: { type: 'keyword' },
    recipient: {
      type: 'object',
      properties: {
        economicCode: { type: 'text' },
        nationalCode: { type: 'text' },
        address: { type: 'text' },
        phone: { type: 'text' },
        registrationNo: { type: 'text' },
        postalCode: { type: 'text' },
        name: { type: 'text' },
        refId: { type: 'keyword' },
        financialId: { type: 'keyword' },
        lastname: { type: 'text' },
      },
    },
    invoiceNo: { type: 'text' },
    issueNo: { type: 'text' },
    discount: { type: 'float' }, 
    duty: { type: 'integer' }, 
    additionalFee: { type: 'integer' }, 
    isCash: { type: 'boolean' }, 
    financialDocumentId: { type: 'text' },
    total: { type: 'float' }, 
    tax: { type: 'float' }, 
    createdBy: { type: 'keyword' },
    issuedBy: { type: 'keyword' },
    updatedBy: { type: 'keyword' },
    yearOfCreatedAt: { type: 'integer' },
    monthOfCreatedAt: { type: 'integer' },
    dayOfCreatedAt: { type: 'integer' },
    createdAt: {type: 'date'},
    updatedAt: {type: 'date'},
    yearOfExpiryAt: { type: 'integer' },
    monthOfExpiryAt: { type: 'integer' },
    dayOfExpiryAt: { type: 'integer' },
    yearOfIssuedAt: { type: 'integer' },
    monthOfIssuedAt: { type: 'integer' },
    dayOfIssuedAt: { type: 'integer' },
  },
};
